### ISSUE TITLE
Conda Linux CI broken late March 2025

### ISSUE THREAD

**Issue by davidegorbani** [ami-iit/biomechanical-analysis-framework#69]
The `Ubuntu` and `MacOs` CIs are failing due to the same error:

```
CMake Error at /home/runner/micromamba/envs/biomechanical-analysis-framework/lib/cmake/vtk-9.3/VTK-targets.cmake:1543 (message):
  The imported target "VTK::IOFFMPEG" references the file

     "/home/runner/micromamba/envs/biomechanical-analysis-framework/lib/libvtkIOFFMPEG-9.3.so.9.3"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/runner/micromamba/envs/biomechanical-analysis-framework/lib/cmake/vtk-9.3/VTK-targets.cmake"

  but not all the files it references.
```

CC @traversaro

**Comment by traversaro** [comment]
Argh, can you try to install `vtk` instead of `vtk-base` ?

**Comment by traversaro** [comment]
The issue is unfortunately intricated and will be fixed by https://github.com/conda-forge/admin-requests/pull/1452, however this will take some time, I would expect at least the us west coast work day. As a temporary workaround, we can just pin pcl to `1.15.0==*_0`.

**Comment by traversaro** [comment]
> The issue is unfortunately intricated and will be fixed by [conda-forge/admin-requests#1452](https://github.com/conda-forge/admin-requests/pull/1452), however this will take some time, I would expect at least the us west coast work day. As a temporary workaround, we can just pin pcl to `1.15.0==*_0`.

The PR was merged by somebody in Europe, so I think the issue is now fixed even without https://github.com/ami-iit/biomechanical-analysis-framework/pull/70 .

**Comment by davidegorbani** [comment]
> The PR was merged by somebody in Europe, so I think the issue is now fixed even without [#70](https://github.com/ami-iit/biomechanical-analysis-framework/pull/70) .

Do we have to wait for some time? Because I see that the CI is still failing in https://github.com/ami-iit/biomechanical-analysis-framework/actions/runs/14032396021/job/39283827352?pr=68.

**Comment by davidegorbani** [comment]
Closing as now CI is passing (see https://github.com/ami-iit/biomechanical-analysis-framework/actions/runs/14033306479).

**Comment by traversaro** [comment]
> > The PR was merged by somebody in Europe, so I think the issue is now fixed even without [#70](https://github.com/ami-iit/biomechanical-analysis-framework/pull/70) .
> 
> Do we have to wait for some time? Because I see that the CI is still failing in https://github.com/ami-iit/biomechanical-analysis-framework/actions/runs/14032396021/job/39283827352?pr=68.

Yes, that is due to CDN propagation.
